version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    env_file: ./backend/.env
    environment:
      - DB_HOST=postgresdb
      - DB_USER="app"
      - DB_PASSWORD="changethis123"
      - DB_NAME="app"
      - DB_PORT=5432
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    container_name: postgresdb
    environment:
      - POSTGRES_PASSWORD=changethis123
      - POSTGRES_USER=app
      - POSTGRES_DB=app
    volumes:
      - pgdata:/var/lib/postgresql/data 
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  nginxproxymanamger:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '8090:81'
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    environment:
      - DISABLE_IPV6=true

volumes:
  pgdata: